// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625174745_AddAiSummaryToScoreEvaluation")]
    partial class AddAiSummaryToScoreEvaluation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("API.Models.ApprovalWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HrApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HrNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LegalApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegalNotes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("ApprovalWorkflows");
                });

            modelBuilder.Entity("API.Models.ScoreEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasEsgCertification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasIncompleteFiscalDocs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasJudicialOrLaborProcess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPositiveInternalHistory")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PostDeliveryDeadlineScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PostDeliveryPriceScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PostDeliveryQualityScore")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("ScoreEvaluations");
                });

            modelBuilder.Entity("API.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("API.Models.ApprovalWorkflow", b =>
                {
                    b.HasOne("API.Models.Supplier", "Supplier")
                        .WithOne("ApprovalWorkflow")
                        .HasForeignKey("API.Models.ApprovalWorkflow", "SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("API.Models.ScoreEvaluation", b =>
                {
                    b.HasOne("API.Models.Supplier", "Supplier")
                        .WithOne("ScoreEvaluation")
                        .HasForeignKey("API.Models.ScoreEvaluation", "SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("API.Models.Supplier", b =>
                {
                    b.Navigation("ApprovalWorkflow");

                    b.Navigation("ScoreEvaluation");
                });
#pragma warning restore 612, 618
        }
    }
}
